---
- name: Build custom Docker image with Web and DB server
  hosts: all
  become: yes

  tasks:
    - name: Copy Dockerfile to remote host
      copy:
        src: Dockerfile
        dest: /tmp/Dockerfile

    - name: Build Docker image from Dockerfile
      command: docker build -t web-db-server /tmp/
      args:
        chdir: /tmp

    - name: Run the web-db container
      command: |
        docker run -d \
          --name web-db-container \
          -p 8080:80 \
          -p 3306:3306 \
          web-db-server

    - name: Verify container is running
      command: docker ps
      register: container_list

    - name: Display running containers
      debug:
        var: container_list.stdout
